### ISSUE TITLE
Getting 502 when running a deployment rolling update

### ISSUE THREAD

**Issue by idanya** [kubernetes-sigs/aws-alb-ingress-controller#1124]
When running a rolling update of a deployment, the ALB returns a lot of 502's. 
Seems like the ALB is not synced to the actual pod state in k8s.

I can see that when a pod is being replaced, the alb controller registers the new pod in the target group and removes the old one. The problem is that the ALB state is for the new pod is `initial` and for the old one is `draining` - causing the service to be unavailable and return 502.  

Service is completely unavailable when it's a single pod service, with bigger services with multiple pods I can see there is a spike in 502's which resolves itself after a while (all new pods gets to the healthy state in the alb).

Ideally, the old pod should not terminate before the new one gets to a `healthy` state in the ALB. Of course, k8s is not aware of that. 

Is this a known issue? any acceptable workarounds?

**Comment by gaganapplatix** [comment]
You need the readiness gate if you are on flat networking and Pods are direct targets for the ALB. There is a PR sitting around which needs to be merged for this

https://github.com/kubernetes-sigs/aws-alb-ingress-controller/pull/955

Without that the deployment controller will move forward with its rolling updates regardless of whether target groups are up to date with regard to the new pods.

**Comment by wadefelix** [comment]
don't update the service.

**Comment by vedatappsamurai** [comment]
Is there any update on this as #955 is merged now? We've updated ALB Ingress Controller to v1.1.6 and we're still getting 502/504's whenever HPA terminates a pod receiving requests. We kept 30 second sleeps just in case v1.1.6 did not fix it, but we've received 502/504's regardless.

**Comment by M00nF1sh** [comment]
@wadefelix i believe this is fixed with pod readiness probe. 
The caveat is you need to add the pod readiness probe manually for now and do a sleep. 

Sample pod spec:
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-dp
spec:
  replicas: 200
  selector:
    matchLabels:
      app: my-dp
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: my-dp
    spec:
      readinessGates:
      - conditionType: target-health.alb.ingress.k8s.aws/my-ingress_my-dp_80
      containers:
      - name: server
        image: xx
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: MESSAGE
          value: The Doctor
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 40"]
      terminationGracePeriodSeconds: 70
```

**Comment by billyshambrook** [comment]
@M00nF1sh what's the purpose for the lifecycle hook if we have the pod readiness gate?

**Comment by M00nF1sh** [comment]
@billyshambrook pod readiness gate only guarantee you always have pods for new connection during deployment(e.g. when controller experiencing timeouts for AWS APIs, the deployment is paused). 
But it don't protect existing connection and new connection to old pods. Controller deregisterTarget takes time, ALB propagate targets changes to its nodes takes time.

**Comment by billyshambrook** [comment]
Thanks @M00nF1sh for the fast response. Does kubernetes provide a hook like pod readiness gate but for when a external process (alb in this case) has finished before it starts to terminate without having to rely on a sleep? Though you would then need to have a way of knowing once the ALB has propagated the drain request...

Just wondering what would be the next steps to take to harden this even more

**Comment by M00nF1sh** [comment]
@billyshambrook 
Currently the only thing to prevent pod container deletion is lifecycleHooks. (finalizer won't work).
Ideally the lifecyleHook can query a in-cluster service hosted by this controller for removal status(too complicated than a 40 sec sleep TBH :D) (Adjust the 40 sec to match deregistration delay)

**Comment by wadefelix** [comment]
> @wadefelix i believe this is fixed with pod readiness probe.
> The caveat is you need to add the pod readiness probe manually for now with a 40 sec sleep.
> 
> If it don't work, please send me with a repro case.
> 
> Sample pod spec:
> 
> ```
> apiVersion: apps/v1
> kind: Deployment
> metadata:
>   name: my-dp
> spec:
>   replicas: 200
>   selector:
>     matchLabels:
>       app: my-dp
>   strategy:
>     type: RollingUpdate
>   template:
>     metadata:
>       labels:
>         app: my-dp
>     spec:
>       readinessGates:
>       - conditionType: target-health.alb.ingress.k8s.aws/my-ingress_my-dp_80
>       containers:
>       - name: server
>         image: xx
>         imagePullPolicy: Always
>         ports:
>         - containerPort: 8080
>         env:
>         - name: MESSAGE
>           value: The Doctor
>         lifecycle:
>           preStop:
>             exec:
>               command: ["/bin/sh", "-c", "sleep 40"]
>       terminationGracePeriodSeconds: 70
> ```

If the svc object is update/recreate, the nodePort is changed by eks, So the alb cannot redirect the requests to the old pods.

**Comment by idanya** [comment]
Fixed in v1.1.6 with readiness gates #955

**Comment by varuzam** [comment]
The problem is still actual. 
I use v2.1.3. and only lifecycle preStop helped to avoid 50x errors during deploy.

**Comment by simmessa** [comment]
I can confirm what  @varuzam said, this issue is still here and having a workaround like that as our only option for zero downtime on EKS + ALB controller is frankly unacceptable for what aims to be "enterprise-grade", hopefully something will be done about this.

**Comment by ajaymdesai** [comment]
We are running into this every time we deploy 502 alarms from our upstream services

**Comment by robinmonjo** [comment]
Facing the exact same issue, would love to have a proper solution to this 😊

**Comment by abolychev** [comment]
Same issue.
aws-load-balancer-controller:v2.10.0
Server Version: v1.31.7-eks-4096722
